package tel.core.s1ap.spec;

import java.util.Arrays;

/**
 * S1AP protocol IE identifiers from 3GPP TS 36.413.
 */
public enum ProtocolIeId {
    MME_UE_S1AP_ID(0), HANDOVER_TYPE(1), CAUSE(2), SOURCE_ID(3), TARGET_ID(4),
    ENB_UE_S1AP_ID(8), E_RAB_SUBJECT_TO_DATA_FORWARDING_LIST(12), E_RAB_TO_RELEASE_LIST_HO_CMD(13),
    E_RAB_DATA_FORWARDING_ITEM(14), E_RAB_RELEASE_ITEM_BEARER_REL_COMP(15),
    E_RAB_TO_BE_SETUP_LIST_BEARER_SU_REQ(16), E_RAB_TO_BE_SETUP_ITEM_BEARER_SU_REQ(17),
    E_RAB_ADMITTED_LIST(18), E_RAB_FAILED_TO_SETUP_LIST_HO_REQ_ACK(19), E_RAB_ADMITTED_ITEM(20),
    E_RAB_FAILED_TO_SETUP_ITEM_HO_REQ_ACK(21), E_RAB_TO_BE_SWITCHED_DL_LIST(22),
    E_RAB_TO_BE_SWITCHED_DL_ITEM(23), E_RAB_TO_BE_SETUP_LIST_CTXT_SU_REQ(24), TRACE_ACTIVATION(25),
    NAS_PDU(26), E_RAB_TO_BE_SETUP_ITEM_HO_REQ(27), E_RAB_SETUP_LIST_BEARER_SU_RES(28),
    E_RAB_FAILED_TO_SETUP_LIST_BEARER_SU_RES(29), E_RAB_TO_BE_MODIFIED_LIST_BEARER_MOD_REQ(30),
    E_RAB_MODIFY_LIST_BEARER_MOD_RES(31), E_RAB_FAILED_TO_MODIFY_LIST(32), E_RAB_TO_BE_RELEASED_LIST(33),
    E_RAB_FAILED_TO_RELEASE_LIST(34), E_RAB_ITEM(35), E_RAB_TO_BE_MODIFIED_ITEM_BEARER_MOD_REQ(36),
    E_RAB_MODIFY_ITEM_BEARER_MOD_RES(37), E_RAB_RELEASE_ITEM(38), E_RAB_SETUP_ITEM_BEARER_SU_RES(39),
    SECURITY_CONTEXT(40), HANDOVER_RESTRICTION_LIST(41), UE_PAGING_ID(43), PAGING_DRX(44), TAI_LIST(46),
    TAI_ITEM(47), E_RAB_FAILED_TO_SETUP_LIST_CTXT_SU_RES(48), E_RAB_RELEASE_ITEM_HO_CMD(49),
    E_RAB_SETUP_ITEM_CTXT_SU_RES(50), E_RAB_SETUP_LIST_CTXT_SU_RES(51),
    E_RAB_TO_BE_SETUP_ITEM_CTXT_SU_REQ(52), E_RAB_TO_BE_SETUP_LIST_HO_REQ(53),
    GERAN_TO_LTEHO_INFORMATION_RES(55), UTRAN_TO_LTEHO_INFORMATION_RES(57), GLOBAL_ENB_ID(59), ENB_NAME(60),
    MME_NAME(61), SERVED_PLMNS(63), SUPPORTED_TAS(64), TIME_TO_WAIT(65),
    U_E_AGGREGATE_MAXIMUM_BITRATE(66), TAI(67), E_RAB_RELEASE_LIST_BEARER_REL_COMP(69), CDMA2000PDU(70),
    CDMA2000RAT_TYPE(71), CDMA2000SECTOR_ID(72), SECURITY_KEY(73), UE_RADIO_CAPABILITY(74), GUMMEI_ID(75),
    E_RAB_INFORMATION_LIST_ITEM(78), DIRECT_FORWARDING_PATH_AVAILABILITY(79), UE_IDENTITY_INDEX_VALUE(80),
    CDMA2000HO_STATUS(83), CDMA2000HO_REQUIRED_INDICATION(84), E_UTRAN_TRACE_ID(86),
    RELATIVE_MME_CAPACITY(87), SOURCE_MME_UE_S1AP_ID(88), BEARERS_SUBJECT_TO_STATUS_TRANSFER_ITEM(89),
    E_NB_STATUS_TRANSFER_TRANSPARENT_CONTAINER(90), UE_ASSOCIATED_LOGICAL_S1_CONNECTION_ITEM(91), RESET_TYPE(92),
    UE_ASSOCIATED_LOGICAL_S1_CONNECTION_LIST_RES_ACK(93), E_RAB_TO_BE_SWITCHED_UL_ITEM(94),
    E_RAB_TO_BE_SWITCHED_UL_LIST(95), S_TMSI(96), CDMA2000ONE_XRAND(97), REQUEST_TYPE(98), UE_S1AP_IDS(99),
    E_UTRAN_CGI(100), OVERLOAD_RESPONSE(101), CDMA2000ONE_XSRVCC_INFO(102),
    E_RAB_FAILED_TO_BE_RELEASED_LIST(103), SOURCE_TO_TARGET_TRANSPARENT_CONTAINER(104), SERVED_GUMMEIS(105),
    SUBSCRIBER_PROFILE_IDFOR_RFP(106), UE_SECURITY_CAPABILITIES(107), CS_FALLBACK_INDICATOR(108), CN_DOMAIN(109),
    E_RAB_RELEASED_LIST(110), MESSAGE_IDENTIFIER(111), SERIAL_NUMBER(112), WARNING_AREA_LIST(113),
    REPETITION_PERIOD(114), NUMBEROF_BROADCAST_REQUEST(115), WARNING_TYPE(116), WARNING_SECURITY_INFO(117),
    DATA_CODING_SCHEME(118), WARNING_MESSAGE_CONTENTS(119), BROADCAST_COMPLETED_AREA_LIST(120),
    INTER_SYSTEM_INFORMATION_TRANSFER_TYPE_EDT(121), INTER_SYSTEM_INFORMATION_TRANSFER_TYPE_MDT(122),
    TARGET_TO_SOURCE_TRANSPARENT_CONTAINER(123), SRVCC_OPERATION_POSSIBLE(124), SRVCCHO_INDICATION(125),
    NAS_DOWNLINK_COUNT(126), CSG_ID(127), CSG_ID_LIST(128), SON_CONFIGURATION_TRANSFER_ECT(129),
    SON_CONFIGURATION_TRANSFER_MCT(130), TRACE_COLLECTION_ENTITY_IP_ADDRESS(131), MS_CLASSMARK2(132),
    MS_CLASSMARK3(133), RRC_ESTABLISHMENT_CAUSE(134), NAS_SECURITY_PARAMETERSFROM_E_UTRAN(135),
    NAS_SECURITY_PARAMETERSTO_E_UTRAN(136), DEFAULT_PAGING_DRX(137),
    SOURCE_TO_TARGET_TRANSPARENT_CONTAINER_SECONDARY(138), TARGET_TO_SOURCE_TRANSPARENT_CONTAINER_SECONDARY(139),
    E_UTRAN_ROUND_TRIP_DELAY_ESTIMATION_INFO(140), BROADCAST_CANCELLED_AREA_LIST(141),
    CONCURRENT_WARNING_MESSAGE_INDICATOR(142), DATA_FORWARDING_NOT_POSSIBLE(143), EXTENDED_REPETITION_PERIOD(144),
    CELL_ACCESS_MODE(145), LP_PA_PDU(147), ROUTING_ID(148), TIME_SYNCHRONISATION_INFO(149),
    PS_SERVICE_NOT_AVAILABLE(150), PAGING_PRIORITY(151), X2TNL_CONFIGURATION_INFO(152),
    E_NBX2EXTENDED_TRANSPORT_LAYER_ADDRESSES(153), GUMMEI_LIST(154), GW_TRANSPORT_LAYER_ADDRESS(155),
    CORRELATION_ID(156), SOURCE_MME_GUMMEI(157), MME_UE_S1AP_ID_2(158), REGISTERED_LAI(159),
    RELAY_NODE_INDICATOR(160), TRAFFIC_LOAD_REDUCTION_INDICATION(161), MDT_CONFIGURATION(162),
    MME_RELAY_SUPPORT_INDICATOR(163), GW_CONTEXT_RELEASE_INDICATION(164), MANAGEMENT_BASED_MDT_ALLOWED(165),
    PRIVACY_INDICATOR(166), TIME_UE_STAYED_IN_CELL_ENHANCED_GRANULARITY(167), HO_CAUSE(168),
    VOICE_SUPPORT_MATCH_INDICATOR(169), GUMMEI_TYPE(170), M3CONFIGURATION(171), M4CONFIGURATION(172),
    M5CONFIGURATION(173), MDT_LOCATION_INFO(174), MOBILITY_INFORMATION(175), TUNNEL_INFORMATION_FOR_BBF(176),
    MANAGEMENT_BASED_MDTPLMN_LIST(177), SIGNALLING_BASED_MDTPLMN_LIST(178), ULCOUNT_VALUE_EXTENDED(179),
    DLCOUNT_VALUE_EXTENDED(180), RECEIVE_STATUS_OF_ULPDCPSDU_US_EXTENDED(181), ECGI_LIST_FOR_RESTART(182),
    SIPTO_CORRELATION_ID(183), SIPTO_L_GW_TRANSPORT_LAYER_ADDRESS(184), TRANSPORT_INFORMATION(185), LHN_ID(186),
    ADDITIONAL_CS_FALLBACK_INDICATOR(187), TAI_LIST_FOR_RESTART(188), USER_LOCATION_INFORMATION(189),
    EMERGENCY_AREA_ID_LIST_FOR_RESTART(190), KILL_ALL_WARNING_MESSAGES(191), MASKED_IMEISV(192),
    E_NB_INDIRECT_X2TRANSPORT_LAYER_ADDRESSES(193), U_E_HISTORY_INFORMATION_FROM_THE_UE(194),
    PRO_SE_AUTHORIZED(195), EXPECTED_UE_BEHAVIOUR(196), LOGGED_MBSFNMDT(197), UE_RADIO_CAPABILITY_FOR_PAGING(198),
    E_RAB_TO_BE_MODIFIED_LIST_BEARER_MOD_IND(199), E_RAB_TO_BE_MODIFIED_ITEM_BEARER_MOD_IND(200),
    E_RAB_NOT_TO_BE_MODIFIED_LIST_BEARER_MOD_IND(201), E_RAB_NOT_TO_BE_MODIFIED_ITEM_BEARER_MOD_IND(202),
    E_RAB_MODIFY_LIST_BEARER_MOD_CONF(203), E_RAB_MODIFY_ITEM_BEARER_MOD_CONF(204),
    E_RAB_FAILED_TO_MODIFY_LIST_BEARER_MOD_CONF(205), SON_INFORMATION_REPORT(206),
    MUTING_AVAILABILITY_INDICATION(207), MUTING_PATTERN_INFORMATION(208), SYNCHRONISATION_INFORMATION(209),
    E_RAB_TO_BE_RELEASED_LIST_BEARER_MOD_CONF(210), ASSISTANCE_DATA_FOR_PAGING(211),
    CELL_IDENTIFIER_AND_CE_LEVEL_FOR_CE_CAPABLE_U_ES(212),
    INFORMATION_ON_RECOMMENDED_CELLS_AND_EN_BS_FOR_PAGING(213), RECOMMENDED_CELL_ITEM(214),
    RECOMMENDED_ENB_ITEM(215), PRO_SE_UE_TO_NETWORK_RELAYING(216), ULCOUNT_VALUE_PDCP_S_NLENGTH18(217),
    DLCOUNT_VALUE_PDCP_S_NLENGTH18(218), RECEIVE_STATUS_OF_ULPDCPSDU_US_PDCP_S_NLENGTH18(219),
    M6CONFIGURATION(220), M7CONFIGURATION(221), PW_FAILED_ECGI_LIST(222), MME_GROUP_ID(223), ADDITIONAL_GUTI(224),
    S1_MESSAGE(225), CSG_MEMBERSHIP_INFO(226), PAGING_E_DRX_INFORMATION(227), UE_RETENTION_INFORMATION(228),
    UE_USAGE_TYPE(230), EXTENDED_UE_IDENTITY_INDEX_VALUE(231), RAT_TYPE(232), BEARER_TYPE(233),
    NB_IO_T_DEFAULT_PAGING_DRX(234), E_RAB_FAILED_TO_RESUME_LIST_RESUME_REQ(235),
    E_RAB_FAILED_TO_RESUME_ITEM_RESUME_REQ(236), E_RAB_FAILED_TO_RESUME_LIST_RESUME_RES(237),
    E_RAB_FAILED_TO_RESUME_ITEM_RESUME_RES(238), NB_IO_T_PAGING_E_DRX_INFORMATION(239),
    V2X_SERVICES_AUTHORIZED(240), SRVCC_OPERATION_NOT_POSSIBLE(243), RRC_RESUME_CAUSE(245), DCN_ID(246),
    DLNASPDU_DELIVERY_ACK_REQUEST(249), ENHANCED_COVERAGE_RESTRICTED(251), UE_LEVEL_QO_S_PARAMETERS(252),
    DL_CP_SECURITY_INFORMATION(253), UL_CP_SECURITY_INFORMATION(254), EXTENDED_E_RAB_MAXIMUM_BITRATE_DL(255),
    EXTENDED_E_RAB_MAXIMUM_BITRATE_UL(256), EXTENDED_E_RAB_GUARANTEED_BITRATE_DL(257),
    EXTENDED_E_RAB_GUARANTEED_BITRATE_UL(258), EXTENDED_U_EAGGREGATE_MAXIMUM_BIT_RATE_DL(259),
    EXTENDED_U_EAGGREGATE_MAXIMUM_BIT_RATE_UL(260), N_RRESTRICTIONIN_EP_SAS_SECONDARY_RAT(261),
    UE_APP_LAYER_MEAS_CONFIG(262), UE_APPLICATION_LAYER_MEASUREMENT_CAPABILITY(263),
    SECONDARY_RAT_DATA_USAGE_REPORT_LIST(264), SECONDARY_RAT_DATA_USAGE_REPORT_ITEM(265), HANDOVER_FLAG(266),
    E_RAB_USAGE_REPORT_ITEM(267), SECONDARY_RAT_DATA_USAGE_REQUEST(268), NRUE_SECURITY_CAPABILITIES(269),
    UNLICENSED_SPECTRUM_RESTRICTION(270), CE_MODE_B_RESTRICTED(271), LTE_M_INDICATION(272),
    DOWNLINK_PACKET_LOSS_RATE(273), UPLINK_PACKET_LOSS_RATE(274), UE_CAPABILITY_INFO_REQUEST(275), SERVICE_TYPE(276),
    AERIAL_U_ESUBSCRIPTION_INFORMATION(277), SUBSCRIPTION_BASED_UE_DIFFERENTIATION_INFO(278), END_INDICATION(280),
    EDT_SESSION(281), CN_TYPE_RESTRICTIONS(282), PENDING_DATA_INDICATION(283),
    BLUETOOTH_MEASUREMENT_CONFIGURATION(284), WLAN_MEASUREMENT_CONFIGURATION(285), WARNING_AREA_COORDINATES(286),
    N_RRESTRICTIONIN5GS(287), PS_CELL_INFORMATION(288), LAST_NG_RANPLMN_IDENTITY(290), CONNECTEDENG_NB_LIST(291),
    CONNECTEDENG_NB_TO_ADD_LIST(292), CONNECTEDENG_NB_TO_REMOVE_LIST(293),
    EN_DCSON_CONFIGURATION_TRANSFER_ECT(294), EN_DCSON_CONFIGURATION_TRANSFER_MCT(295),
    IM_SVOICE_EP_SEALLBACKEROM5G(296), TIME_SINCE_SECONDARY_NODE_RELEASE(297), REQUEST_TYPE_ADDITIONAL_INFO(298),
    CRITICALITY_DIAGNOSTICS(58), CSG_MEMBERSHIP_STATUS(146),
    UE_USER_PLANE_CIOT_SUPPORT_INDICATOR(241), CE_MODE_B_SUPPORT_INDICATOR(242),
    NB_IOT_UE_IDENTITY_INDEX_VALUE(244), SERVED_DCNS(247), UE_SIDELINK_AGGREGATE_MAXIMUM_BITRATE(248),
    COVERAGE_LEVEL(250),
    UNKNOWN(-1);

    private final int value;

    ProtocolIeId(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public static ProtocolIeId valueOf(int value) {
        return Arrays.stream(values()).filter(id -> id.value == value).findFirst().orElse(UNKNOWN);
    }
}
